name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  fleather: ^1.26.0
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  local_auth: ^2.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "lib/assets/notetaking_notepad.png"
  windows:
    generate: true
    image_path: "lib/assets/notetaking_notepad.ico"
